### ISSUE TITLE
Logic Apps v2 VS Code Extension doesn't work in VS Codespaces

### ISSUE THREAD

**Issue by liliankasem** [Azure/logicapps#237]
Hello! I am unable to use the designer view using the [new VS Code extension ](https://marketplace.visualstudio.com/items?itemName=ms-azuretools.vscode-azurelogicapps). The error I get says `Workflow design time could not be started`, and when I click on `View output`, I just see a blank page.

I made sure to use a real storage account connection string inside the `local.settings.json` file, so I'm pretty sure that is not the issue.

[Here's the repo I'm using](https://github.com/liliankasem/logicapps) if you would like to test it out yourself.

@TylerLeonhardt: any thoughts on what the issue could be?

![Screen Shot 2021-02-01 at 10 48 42 AM](https://user-images.githubusercontent.com/2198905/106522132-137f9d80-6494-11eb-96da-2bb332f1c662.png)

![Screen Shot 2021-02-01 at 10 49 15 AM](https://user-images.githubusercontent.com/2198905/106522161-1c706f00-6494-11eb-8739-d2abce915270.png)

![Screen Shot 2021-02-01 at 10 56 54 AM](https://user-images.githubusercontent.com/2198905/106522184-24301380-6494-11eb-9c89-8c3d3db80361.png)

**Comment by bamurtaugh** [comment]
One note since I'm not sure by the issue title - are you using the [GitHub Codespaces extension](https://marketplace.visualstudio.com/items?itemName=GitHub.codespaces) (rather than Visual Studio Codespaces)? Not sure if the problem relates to that specifically, but the GitHub Codespaces extension is the one we want to use.

**Comment by liliankasem** [comment]
Yes, GitHub codespaces extension and codespaces in the browser too

**Comment by vikash-anand** [comment]
@liliankasem The error message "func not found" means that the system is not able to find the "function core tools" on your machine. Have you installed the Azure Functions core tools on your machine? Here is the list of prerequisites required for Logic App Preview: https://docs.microsoft.com/en-us/azure/logic-apps/create-stateful-stateless-workflows-visual-studio-code#tools

**Comment by liliankasem** [comment]
Yup, I still get the same issue with func tools installed. We think this is the issue:

https://github.com/microsoft/vscode-azurelogicapps/pull/193

**Comment by TylerLeonhardt** [comment]
Yeah changing the `Draft.min.js` file in the `dist` of the extension to `draft.min.js` got it working. The PR basically does that. We did see some strange behavior around port where occasionally port 8000 was forwarded to a random 3XXXX port number instead of 8000... but then reopening the designer seemed to fix that. @bamurtaugh, I'm not sure if that's a vscode remote issue or not... @liliankasem could hit that like 50% of the time, me maybe 30% of the time.

**Comment by bamurtaugh** [comment]
To clarify - the remote explorer read something like `8000 -> 127.0.0.1:3XXXX` (instead of `8000 -> 127.0.0.1:8000` as expected) during those runs? Sometimes I still face issues where I'm notified about an incorrect/unexpected 3XXXX port, i.e. a debugging port, but my expected port is still available in the remote explorer and browser, so just making sure I'm understanding correctly.

Sounds similar to https://github.com/microsoft/vssaas-planning/issues/1788 (and specifically point 2 here https://github.com/microsoft/vssaas-planning/issues/1788#issuecomment-743174588).

**Comment by TylerLeonhardt** [comment]
Yeah I think you're right @bamurtaugh... thought it doesn't exactly explain why the webview doesn't render when the notification says the `3XXXX` (correlation not causation)...

**Comment by bamurtaugh** [comment]
I think the issues are independent - it sounds like webview/rendering issues have to do with how the Logic Apps extension works in Codespaces, but I wouldn't think that's related to ports, especially since we're seeing the ports issue in non-Logic Apps or webview-related issues (unless you're saying the webview _only_ doesn't render when the notification incorrectly reads `3XXX`, in which case that'd be interesting).

**Comment by TylerLeonhardt** [comment]
> unless you're saying the webview only doesn't render when the notification incorrectly reads 3XXX, in which case that'd be interesting

Right that's what we are seeing... though I don't know enough to say it's vscode's fault.

**Comment by bamurtaugh** [comment]
Oh interesting! Hmmm - sounds like it'd be worth filing an issue in https://github.com/microsoft/vssaas-planning/issues, or commenting on https://github.com/microsoft/vssaas-planning/issues/1788 to explain the interesting pivot here and get some perspectives/visibility from Codespaces & VS Code folks.

**Comment by joechung-msft** [comment]
I merged the fix for the Draft script filename casing. It should be included in the next extension release (0.0.9).

**Comment by joechung-msft** [comment]
Closing this now that 0.0.9 is released. Let us know if any follow-up is required for the port issues.

**Comment by TylerLeonhardt** [comment]
@joechung-msft I still see 0.0.8 here: https://marketplace.visualstudio.com/items?itemName=ms-azuretools.vscode-azurelogicapps

![image](https://user-images.githubusercontent.com/2644648/108143243-37d69f00-707c-11eb-87a1-2638b943cbdc.png)

not sure if that's expected

**Comment by joechung-msft** [comment]
0.0.9 is currently in the process of being tested and released. ETA is next week.
